### ISSUE TITLE
CreateContext vs Redux

### ISSUE THREAD

**Issue by parksj10** [LightTag/dcjs-in-react#2]
Hi tal,

Great article for DC/React, one of a kind! Did you guys end up using it? Quick question, was there a reason you were using react context providers instead of redux? I'm seeing some performance issues when I cloned the repo and I'm wondering if they would be remedied by using a redux oriented state management system for the crossfilter index

Best,
Josh

**Comment by talolard** [comment]
Hi,
We never deployed this to production mostly for prioritization reasons. 

We try to move away from Redux as much as possible, because of a preference for "data locality". 

Context consumers re-render on every change, which can be problematic. You can work around that as follows: 
I quick trick to solve performance problems with context consumers is to make an intermediate component. 
eg instead of
```jsx
Child =()=>{
context = useContext()
...
}
```

Do 
```jsx
const Child = (props)=>{
 const {context} = props; 
... 
}

const ChildWrapper = () =>{
 const context = useContext(...);
return <Child context={context} />
}

**Comment by parksj10** [comment]
Hi Tal,

Thanks a lot for the reply! I know how that goes with prioritization… Very cool project though, and thanks again for sharing. I’ve read that Redux scales much better than useContext, but perhaps I’m reading in the wrong places. I’ll likely give both a try and see if/what the performance differences are!
